#!/usr/bin/bash

source venv/bin/activate

pycodestyle efj_parser tests
if [ $? -ne "0" ]
then
    exit 1
fi

mypy efj_parser tests
if [ $? -ne "0" ]
then
    exit 2
fi

pyflakes3 efj_parser tests
if [ $? -ne "0" ]
then
    exit 3
fi

cd tests
python -m unittest
if [ $? -ne "0" ]
then
    exit 4
fi
